"""
Gmail client using OAuth2 refresh token (works with personal @gmail.com).
Auth is handled by the token file generated by scripts/gmail_auth.py.
"""
import os, base64, email as email_lib
from typing import Optional
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

import config

SCOPES = [
    "https://www.googleapis.com/auth/gmail.readonly",
    "https://www.googleapis.com/auth/gmail.send",
    "https://www.googleapis.com/auth/gmail.modify",
]


class GmailClient:
    def __init__(self):
        self._service = None

    def _get_service(self):
        """Return an authenticated Gmail service, refreshing token if needed."""
        if self._service:
            return self._service

        token_file = config.GMAIL_TOKEN_FILE
        if not os.path.exists(token_file):
            raise RuntimeError(
                f"Gmail token not found at {token_file}. "
                "Run: python scripts/gmail_auth.py"
            )

        creds = Credentials.from_authorized_user_file(token_file, SCOPES)

        if not creds.valid:
            if creds.expired and creds.refresh_token:
                creds.refresh(Request())
                # Persist the refreshed token
                with open(token_file, "w") as f:
                    f.write(creds.to_json())
            else:
                raise RuntimeError("Gmail token expired. Re-run scripts/gmail_auth.py")

        self._service = build("gmail", "v1", credentials=creds)
        return self._service

    # ── Read ──────────────────────────────────────────────────────────────────

    def get_unread_contact_form_emails(self) -> list[dict]:
        """
        Returns list of unread messages matching our contact-form label/filter.
        Each dict has: id, subject, sender, body_html, body_text, raw_headers
        """
        svc = self._get_service()

        # Search inbox for unread contact-form submissions by subject pattern.
        # We do NOT filter by the nexus-contact-form label here because Gmail
        # never applies that label automatically — it's only applied by Nexus
        # after processing as a "seen" marker.
        query = 'in:inbox is:unread subject:"has made an enquiry"'

        try:
            result = svc.users().messages().list(
                userId="me",
                q=query,
                maxResults=20
            ).execute()
        except HttpError as e:
            print(f"[GmailClient] list error: {e}")
            return []

        messages = result.get("messages", [])
        if not messages:
            return []

        parsed = []
        for msg_stub in messages:
            full = self._fetch_full_message(msg_stub["id"])
            if full:
                parsed.append(full)

        return parsed

    def _fetch_full_message(self, message_id: str) -> Optional[dict]:
        """Fetch and parse a single message into a clean dict."""
        svc = self._get_service()
        try:
            msg = svc.users().messages().get(
                userId="me",
                id=message_id,
                format="full"
            ).execute()
        except HttpError as e:
            print(f"[GmailClient] fetch error {message_id}: {e}")
            return None

        headers = {h["name"].lower(): h["value"] for h in msg["payload"]["headers"]}
        subject = headers.get("subject", "")
        sender  = headers.get("from", "")
        date    = headers.get("date", "")

        body_html = ""
        body_text = ""
        self._extract_body(msg["payload"], body_html, body_text)

        # Re-extract because Python strings are immutable — use lists
        html_parts = []
        text_parts = []
        self._extract_parts(msg["payload"], html_parts, text_parts)
        body_html = "\n".join(html_parts)
        body_text = "\n".join(text_parts)

        return {
            "id":          message_id,
            "thread_id":   msg.get("threadId", ""),
            "subject":     subject,
            "sender":      sender,
            "date":        date,
            "body_html":   body_html,
            "body_text":   body_text,
            "snippet":     msg.get("snippet", ""),
            "label_ids":   msg.get("labelIds", []),
        }

    def _extract_parts(self, payload: dict, html_parts: list, text_parts: list):
        """Recursively extract text/html parts from a MIME payload."""
        mime_type = payload.get("mimeType", "")
        body_data = payload.get("body", {}).get("data", "")

        if body_data:
            decoded = base64.urlsafe_b64decode(body_data + "==").decode("utf-8", errors="replace")
            if "html" in mime_type:
                html_parts.append(decoded)
            elif "text" in mime_type:
                text_parts.append(decoded)

        for part in payload.get("parts", []):
            self._extract_parts(part, html_parts, text_parts)

    def _extract_body(self, payload, html, text):
        pass  # kept for signature compat; real logic in _extract_parts

    # ── Write ─────────────────────────────────────────────────────────────────

    def send_email(
        self,
        to: str,
        subject: str,
        html_body: str,
        text_body: str = "",
        reply_to_thread: Optional[str] = None,
    ) -> bool:
        """Send an email from technobrain6@gmail.com."""
        svc = self._get_service()

        msg = MIMEMultipart("alternative")
        msg["To"]      = to
        msg["From"]    = config.GMAIL_MONITORED_ACCOUNT
        msg["Subject"] = subject

        if text_body:
            msg.attach(MIMEText(text_body, "plain"))
        msg.attach(MIMEText(html_body, "html"))

        raw = base64.urlsafe_b64encode(msg.as_bytes()).decode("utf-8")
        body = {"raw": raw}
        if reply_to_thread:
            body["threadId"] = reply_to_thread

        try:
            svc.users().messages().send(userId="me", body=body).execute()
            return True
        except HttpError as e:
            print(f"[GmailClient] send error: {e}")
            return False

    def mark_as_read(self, message_id: str) -> bool:
        """Remove UNREAD label from a message."""
        svc = self._get_service()
        try:
            svc.users().messages().modify(
                userId="me",
                id=message_id,
                body={"removeLabelIds": ["UNREAD"]}
            ).execute()
            return True
        except HttpError as e:
            print(f"[GmailClient] mark_read error: {e}")
            return False

    def apply_label(self, message_id: str, label_name: str) -> bool:
        """Apply a label by name to a message (resolves name → id automatically)."""
        svc = self._get_service()
        try:
            labels = svc.users().labels().list(userId="me").execute().get("labels", [])
            label_id = next((l["id"] for l in labels if l["name"].lower() == label_name.lower()), None)
            if not label_id:
                return False
            svc.users().messages().modify(
                userId="me",
                id=message_id,
                body={"addLabelIds": [label_id]}
            ).execute()
            return True
        except HttpError as e:
            print(f"[GmailClient] apply_label error: {e}")
            return False

    def ensure_label_exists(self, label_name: str) -> Optional[str]:
        """
        Create the Gmail label if it doesn't exist. Returns the label ID.
        Run once during setup — not on every poll.
        """
        svc = self._get_service()
        labels = svc.users().labels().list(userId="me").execute().get("labels", [])
        for lbl in labels:
            if lbl["name"].lower() == label_name.lower():
                return lbl["id"]

        # Create it
        new_label = svc.users().labels().create(
            userId="me",
            body={
                "name": label_name,
                "labelListVisibility": "labelShow",
                "messageListVisibility": "show",
            }
        ).execute()
        print(f"[GmailClient] Created label '{label_name}' → {new_label['id']}")
        return new_label["id"]

    # ── Gmail Push (production) ────────────────────────────────────────────────

    def register_push_watch(self, pubsub_topic: str) -> dict:
        """
        Register Gmail push notifications via Cloud Pub/Sub.
        Call once — expires after 7 days, must be renewed.
        Only needed for production; polling handles dev.
        """
        svc = self._get_service()
        result = svc.users().watch(
            userId="me",
            body={
                "topicName": pubsub_topic,
                "labelIds": ["INBOX"],
                "labelFilterBehavior": "INCLUDE",
            }
        ).execute()
        return result


# Module-level singleton
gmail = GmailClient()
