"""
Node: fetch_email
Parses the raw Gmail message dict into NexusState fields.
The email body is an HTML table (Image 2 structure).
"""
import re
from bs4 import BeautifulSoup
from agent.state import NexusState


def fetch_email_node(state: NexusState) -> NexusState:
    """
    Extracts structured form fields from the email HTML body.
    Handles both the styled table format (Image 2) and plain text fallback.
    """
    html = state.get("raw_html", "")
    text = state.get("raw_text", "")

    fields = {}

    if html:
        fields = _parse_html_table(html)

    # Fallback: parse plain text
    if not fields.get("email"):
        fields = _parse_plain_text(text)

    # Also try extracting the sender email from the "From" header
    sender_addr = state.get("sender_address", "")
    if not fields.get("email"):
        match = re.search(r"[\w.+-]+@[\w-]+\.[a-zA-Z]+", sender_addr)
        if match:
            fields["email"] = match.group(0)

    # Derive name from subject if not in body
    if not fields.get("name"):
        subject = state.get("subject", "")
        # "John Doe Has Made An Enquiry" → "John Doe"
        m = re.match(r"^(.+?)\s+[Hh]as\s+[Mm]ade", subject)
        if m:
            fields["name"] = m.group(1).strip()

    name_parts = fields.get("name", "").split(" ", 1)

    state["sender_name"]      = fields.get("name", "")
    state["sender_email"]     = fields.get("email", "").lower().strip()
    state["sender_phone"]     = fields.get("phone", "")
    state["message"]          = fields.get("message", "").strip()
    state["product_interest"] = fields.get("product", "")
    state["status_message"]   = f"Parsed email from {state['sender_name'] or state['sender_email']}"

    return state


def _parse_html_table(html: str) -> dict:
    """
    Parse the dark-theme HTML table generated by the Next.js form mailer.
    Structure:
      <tr><td>Name</td></tr>
      <tr><td>John Doe</td></tr>
      <tr><td>Email</td></tr>
      <tr><td>john@example.com</td></tr>
      ...
    """
    soup = BeautifulSoup(html, "lxml")
    rows = soup.find_all("tr")
    fields = {}

    # Build key-value by reading label row then value row
    label_map = {
        "name":         "name",
        "email":        "email",
        "phone/mobile": "phone",
        "phone":        "phone",
        "message":      "message",
        "product":      "product",
        "digital solutions": "product",
        "designation":  "designation",
        "company":      "company",
    }

    pending_key = None
    for row in rows:
        cells = row.find_all("td")
        if not cells:
            continue
        text = cells[0].get_text(strip=True).lower()

        if pending_key:
            value = cells[0].get_text(strip=True)
            fields[pending_key] = value
            pending_key = None
            continue

        for label, key in label_map.items():
            if label in text:
                pending_key = key
                break

    return fields


def _parse_plain_text(text: str) -> dict:
    """Fallback parser for plain-text email bodies."""
    fields = {}
    patterns = {
        "name":    r"(?:Name|Full Name)\s*[:\-]\s*(.+)",
        "email":   r"(?:Email|E-mail)\s*[:\-]\s*(.+)",
        "phone":   r"(?:Phone|Mobile|Tel)\s*[:\-]\s*(.+)",
        "message": r"(?:Message|Enquiry|Query)\s*[:\-]\s*(.+)",
        "product": r"(?:Product|Service|Interested In)\s*[:\-]\s*(.+)",
    }
    for key, pattern in patterns.items():
        m = re.search(pattern, text, re.IGNORECASE)
        if m:
            fields[key] = m.group(1).strip()
    return fields
